version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: domaly/lab_4:compose-app
    container_name: l4_app
    ports:
      - 8000:8000

  test:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    image: domaly/lab_4:compose-test
    container_name: l4_test
    depends_on:
      - app
    network_mode: "host"
